### ISSUE TITLE
Gophish password

### ISSUE THREAD

**Issue by logiboss** [thirdbyte/phish_infra#1]
Hi,

I was testing your infrastructure. It works good, so nice job! The only thing that you probably forgot was that the admin password of the gophish admin panel is already filled in from your database. This means that it will not generate any random password in the logging. You need to give a clean gophish database so the admin user password will be reset. I also inspected the database but unfortunately I only have the hash and can't get the password. Can you look into this.

**Comment by logiboss** [comment]
I removed the line "volume: database etc." now it works.

**Comment by lordhorcrux** [comment]
Yep, You're right. We used "volumes:- ./gophish/gophish.db:/opt/gophish/gophish.db" in the docker compose file for the persistence nature of the campaigns in the gophish. Gophish creates a random password on initial setup. And that gets printed as stdout. To reduce complexities of fetching it from there and have a different initial password everytime, we decided to mount an empty DB with password already set. Will update the README.md to include the password.
